// src/lib/portfolio-data.ts

export const projects = [
  {
    title: 'ProJob',
    slug: 'projob',
    description: 'Detailed project description and images coming soon.',
    imageUrl: 'https://picsum.photos/600/400',
    imageHint: 'modern tech application',
    link: '#',
  },
  {
    title: 'Clevr Sol',
    slug: 'clevr-sol',
    description: 'Detailed project description and images coming soon.',
    imageUrl: 'https://picsum.photos/600/401',
    imageHint: 'solution branding',
    link: '#',
  },
  {
    title: 'Wakesurf Saloon',
    slug: 'wakesurf-saloon',
    description: 'Detailed project description and images coming soon.',
    imageUrl: 'https://picsum.photos/600/402',
    imageHint: 'recreational brand',
    link: '#',
  },
  {
    title: 'Landhacker.AI',
    slug: 'landhacker-ai',
    description: 'AI-powered platform for land investment analysis.',
    imageUrl: 'https://picsum.photos/600/403',
    imageHint: 'AI data analysis',
    link: 'https://landhacker.ai',
  },
  {
    title: 'Lazily.AI',
    slug: 'lazily-ai',
    description: 'AI tools to streamline and automate workflows.',
    imageUrl: 'https://picsum.photos/600/404',
    imageHint: 'automation software',
    link: 'https://lazily.ai',
  },
  {
    title: 'Mystic Vault Society',
    slug: 'mystic-vault-society',
    description: "Marketing and brand strategy for an independent publisher's debut fantasy novel launch.",
    imageUrl: 'https://picsum.photos/600/405',
    imageHint: 'mystical community brand',
    link: 'https://www.mysticvaultsociety.com',
  },
  {
    title: 'The Veilbreakers Crusade',
    slug: 'the-veilbreakers-crusade',
    description: 'A Dungeons & Dragons 5e campaign book and creative IP developed by our founders.',
    imageUrl: 'https://picsum.photos/600/406',
    imageHint: 'fantasy book cover',
    link: '#',
  },
];
